### ISSUE TITLE
Items to be included and order

### ISSUE THREAD

**Issue by danielmlow** [sensein/voice-study#14]
Just to recap and add to what I sent through slack:

Protocol Malargue:
1. protocols/Malargue/README.md
skip introduction.md (we won't have a consent form for this protocol, it will be carried out in person)

2. Microphone check
 activities/VoiceScreening/items/audio_check

3. activities/PHQ-9/

4. from activities/VoiceTask/items/
free_speech_general_mood
say_ah
free_speech_happy
free_speech_sad
free_speech_important_people
free_speech_next_summer
pataka (this is the only one that stop by itself at 10 seconds)

5. A "thank you" page that offers participants to download their speech samples. 

If you prefer, I can add these myself. Would this go in Malargue_context and Malargue_schema?

**Comment by sanuann** [comment]
@danielmlow I will do it. thanks for the details.

**Comment by sanuann** [comment]
@danielmlow what's the time duration for the items in part 4?
